In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [6]:
revenue.shape

(3, 3)

In [8]:
revenue.size

9

In [15]:
profit = revenue - expenses

In [16]:
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

## Using dot products

In [17]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [18]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [19]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])