In [2]:
import numpy as np

# Create

In [21]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 9)
ones = np.ones((2,2,2))

In [22]:
data

array([[[0.45785105, 0.12573722, 0.54063721, 0.31894432],
        [0.58383146, 0.69046972, 0.77125388, 0.61034688],
        [0.7954932 , 0.99371231, 0.55203514, 0.40720616]],

       [[0.84239347, 0.23849668, 0.17056157, 0.31596698],
        [0.20062308, 0.17815197, 0.52443281, 0.65361557],
        [0.59931423, 0.0587008 , 0.1299508 , 0.33171783]]])

In [23]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [24]:
full

array([[[9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9]]])

In [25]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [26]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [27]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [28]:
type(arr)

numpy.ndarray

#  Read

In [29]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [30]:
types

dtype('float64')

In [31]:
shape

(2, 3, 4)

In [33]:
size   #2*3*4

24

In [36]:
data

array([[[0.45785105, 0.12573722, 0.54063721, 0.31894432],
        [0.58383146, 0.69046972, 0.77125388, 0.61034688],
        [0.7954932 , 0.99371231, 0.55203514, 0.40720616]],

       [[0.84239347, 0.23849668, 0.17056157, 0.31596698],
        [0.20062308, 0.17815197, 0.52443281, 0.65361557],
        [0.59931423, 0.0587008 , 0.1299508 , 0.33171783]]])

In [44]:
# Slicing
ar = data[0]
slicer = data[0][0:2]
reverse = data[-1]

#suppose we want to access second value of first row from second array which is 0.23849668
singleval = data[1][0][1]

In [53]:
data

array([[[0.45785105, 0.12573722, 0.54063721, 0.31894432],
        [0.58383146, 0.69046972, 0.77125388, 0.61034688],
        [0.7954932 , 0.99371231, 0.55203514, 0.40720616]],

       [[0.84239347, 0.23849668, 0.17056157, 0.31596698],
        [0.20062308, 0.17815197, 0.52443281, 0.65361557],
        [0.59931423, 0.0587008 , 0.1299508 , 0.33171783]]])

In [45]:
ar

array([[0.45785105, 0.12573722, 0.54063721, 0.31894432],
       [0.58383146, 0.69046972, 0.77125388, 0.61034688],
       [0.7954932 , 0.99371231, 0.55203514, 0.40720616]])

In [46]:
slicer #first two rows of index 0

array([[0.45785105, 0.12573722, 0.54063721, 0.31894432],
       [0.58383146, 0.69046972, 0.77125388, 0.61034688]])

In [47]:
reverse  # will read the last index

array([[0.84239347, 0.23849668, 0.17056157, 0.31596698],
       [0.20062308, 0.17815197, 0.52443281, 0.65361557],
       [0.59931423, 0.0587008 , 0.1299508 , 0.33171783]])

In [62]:
singleval.round(8) # Accessing upto 8th digit after fraction

0.23849668

# Update

In [72]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [73]:
list1

array([0.70011664, 0.06199912, 0.9843525 , 0.52252817, 0.28528306,
       0.03052266, 0.35260594, 0.37932843, 0.81496216, 0.48014658])

In [74]:
list2

array([0.53596592, 0.56206217, 0.07851537, 0.06381286, 0.5148425 ,
       0.31213905, 0.13248904, 0.71804371, 0.22399146, 0.62906064])

In [75]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [76]:
add

array([1.23608256, 0.62406129, 1.06286788, 0.58634103, 0.80012556,
       0.34266171, 0.48509498, 1.09737214, 1.03895362, 1.10920722])

In [77]:
0.21693594*0.19457621

0.0422105730179874

In [78]:
mult

array([0.37523866, 0.03484736, 0.0772868 , 0.03334402, 0.14687584,
       0.00952731, 0.04671642, 0.27237439, 0.18254456, 0.30204132])

In [79]:
dot

1.4807966913757489

In [80]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [86]:
sqrt, ab, power, log #showing all values in one line

(5.0, 2, 128, 3.2188758248682006)

In [87]:
exp

array([ 7.3890561 , 20.08553692])

In [89]:
mins,maxs

(0.030522661439621235, 0.984352503999428)

In [56]:
maxs

0.9300368518784375

In [90]:
data

array([[[0.45785105, 0.12573722, 0.54063721, 0.31894432],
        [0.58383146, 0.69046972, 0.77125388, 0.61034688],
        [0.7954932 , 0.99371231, 0.55203514, 0.40720616]],

       [[0.84239347, 0.23849668, 0.17056157, 0.31596698],
        [0.20062308, 0.17815197, 0.52443281, 0.65361557],
        [0.59931423, 0.0587008 , 0.1299508 , 0.33171783]]])

In [91]:
data[0][0][0] = 700

In [92]:
data

array([[[7.00000000e+02, 1.25737221e-01, 5.40637206e-01, 3.18944315e-01],
        [5.83831456e-01, 6.90469725e-01, 7.71253877e-01, 6.10346880e-01],
        [7.95493204e-01, 9.93712309e-01, 5.52035137e-01, 4.07206156e-01]],

       [[8.42393468e-01, 2.38496678e-01, 1.70561566e-01, 3.15966981e-01],
        [2.00623085e-01, 1.78151965e-01, 5.24432811e-01, 6.53615565e-01],
        [5.99314229e-01, 5.87007955e-02, 1.29950805e-01, 3.31717831e-01]]])

In [96]:
data.sort()
data

array([[[1.25737221e-01, 3.18944315e-01, 5.40637206e-01, 7.00000000e+02],
        [5.83831456e-01, 6.10346880e-01, 6.90469725e-01, 7.71253877e-01],
        [4.07206156e-01, 5.52035137e-01, 7.95493204e-01, 9.93712309e-01]],

       [[1.70561566e-01, 2.38496678e-01, 3.15966981e-01, 8.42393468e-01],
        [1.78151965e-01, 2.00623085e-01, 5.24432811e-01, 6.53615565e-01],
        [5.87007955e-02, 1.29950805e-01, 3.31717831e-01, 5.99314229e-01]]])

In [98]:
print(data.shape)

(2, 3, 4)


In [102]:
data = data.reshape((3,4,2))
data.shape

(3, 4, 2)

In [103]:
data

array([[[1.25737221e-01, 3.18944315e-01],
        [5.40637206e-01, 7.00000000e+02],
        [5.83831456e-01, 6.10346880e-01],
        [6.90469725e-01, 7.71253877e-01]],

       [[4.07206156e-01, 5.52035137e-01],
        [7.95493204e-01, 9.93712309e-01],
        [1.70561566e-01, 2.38496678e-01],
        [3.15966981e-01, 8.42393468e-01]],

       [[1.78151965e-01, 2.00623085e-01],
        [5.24432811e-01, 6.53615565e-01],
        [5.87007955e-02, 1.29950805e-01],
        [3.31717831e-01, 5.99314229e-01]]])

In [106]:
zeroes = np.zeros((6))
print(zeroes)
zeroes = np.append(zeroes, [2,4])
print(zeroes)

[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 2. 4.]


In [108]:
zeroes = np.insert(zeroes, 3, 1)
print(zeroes)

[0. 0. 0. 1. 1. 0. 0. 0. 2. 4.]


# Delete

In [109]:
data

array([[[1.25737221e-01, 3.18944315e-01],
        [5.40637206e-01, 7.00000000e+02],
        [5.83831456e-01, 6.10346880e-01],
        [6.90469725e-01, 7.71253877e-01]],

       [[4.07206156e-01, 5.52035137e-01],
        [7.95493204e-01, 9.93712309e-01],
        [1.70561566e-01, 2.38496678e-01],
        [3.15966981e-01, 8.42393468e-01]],

       [[1.78151965e-01, 2.00623085e-01],
        [5.24432811e-01, 6.53615565e-01],
        [5.87007955e-02, 1.29950805e-01],
        [3.31717831e-01, 5.99314229e-01]]])

In [112]:
np.delete(data, 0, axis=1)

array([[[5.40637206e-01, 7.00000000e+02],
        [5.83831456e-01, 6.10346880e-01],
        [6.90469725e-01, 7.71253877e-01]],

       [[7.95493204e-01, 9.93712309e-01],
        [1.70561566e-01, 2.38496678e-01],
        [3.15966981e-01, 8.42393468e-01]],

       [[5.24432811e-01, 6.53615565e-01],
        [5.87007955e-02, 1.29950805e-01],
        [3.31717831e-01, 5.99314229e-01]]])

In [113]:
np.delete(data, 1, axis=0)

array([[[1.25737221e-01, 3.18944315e-01],
        [5.40637206e-01, 7.00000000e+02],
        [5.83831456e-01, 6.10346880e-01],
        [6.90469725e-01, 7.71253877e-01]],

       [[1.78151965e-01, 2.00623085e-01],
        [5.24432811e-01, 6.53615565e-01],
        [5.87007955e-02, 1.29950805e-01],
        [3.31717831e-01, 5.99314229e-01]]])

In [114]:
np.save("Sample Array", data)

In [115]:
test = np.load("Sample Array.npy")

In [116]:
test

array([[[1.25737221e-01, 3.18944315e-01],
        [5.40637206e-01, 7.00000000e+02],
        [5.83831456e-01, 6.10346880e-01],
        [6.90469725e-01, 7.71253877e-01]],

       [[4.07206156e-01, 5.52035137e-01],
        [7.95493204e-01, 9.93712309e-01],
        [1.70561566e-01, 2.38496678e-01],
        [3.15966981e-01, 8.42393468e-01]],

       [[1.78151965e-01, 2.00623085e-01],
        [5.24432811e-01, 6.53615565e-01],
        [5.87007955e-02, 1.29950805e-01],
        [3.31717831e-01, 5.99314229e-01]]])